## Create FHIR R4 CapStatement Resource


### Outline:

- Source excel with requirements
- pandas to convert in python Ordered Dict
- build json
- generate narrative using Jinja2 templates

### Prerequisites:

- Python 3.6 or greater
- Need to run after conformance resources added to IG and package list created.

### Options: Use global varables below to turn on and off

- add narrative to resources if not using liquid script or IG publisher default
- add ms-table 
- validate

## STEP1: Choose Source Spreadsheet to use

*note:  Jupyteralab and widgets issues: see https://stackoverflow.com/questions/4
9542417/how-to-get-ipywidgets-working-in-jupyter-lab for solution

In [ ]:
#******************** NEED TO UPDATE WHEN Adding new IGS ************************************************

from os import name as os_name
my_base = '/Users/ehaas/' ###if os_name == 'posix' else '//ERICS-AIR-2/ehaas/'


in_path_list = [

        "---pick one below---",
        # "Documents/Python/MyNotebooks/CapStatement/temp_source_spreadsheets/test-spreadsheet.xlsx",
         "Documents/FHIR/US-Core/input/resources_spreadsheets/uscore-client.xlsx",
         "Documents/FHIR/US-Core/input/resources_spreadsheets/uscore-server.xlsx",
         "Documents/FHIR/davinci-alerts/input/resources-spreadsheets/alert-initiator.xlsx",
         "Documents/FHIR/davinci-alerts/input/resources-spreadsheets/alert-receiver.xlsx",
         "Documents/FHIR/davinci-alerts/input/resources-spreadsheets/notification-forwarder.xlsx",
        # "Documents/Python/Jupyter/MyNotebooks/CapStatement/temp_source_spreadsheets/2022-10-26_DEQM/DEQM_Capability_Statement_Consumer_Client.xlsx",
        # "Documents/Python/Jupyter/MyNotebooks/CapStatement/temp_source_spreadsheets/2022-10-26_DEQM/DEQM_Capability_Statement_Consumer_Server.xlsx",
        # "Documents/Python/Jupyter/MyNotebooks/CapStatement/temp_source_spreadsheets/2022-10-26_DEQM/DEQM_Capability_Statement_GIC_Receiver_Server.xlsx",
        # "Documents/Python/Jupyter/MyNotebooks/CapStatement/temp_source_spreadsheets/2022-10-26_DEQM/DEQM_Capability_Statement_GIC_Reporter_Client.xlsx",
        # "Documents/Python/Jupyter/MyNotebooks/CapStatement/temp_source_spreadsheets/2022-10-26_DEQM/DEQM_Capability_Statement_Producer_Client.xlsx",
        # "Documents/Python/Jupyter/MyNotebooks/CapStatement/temp_source_spreadsheets/2022-10-26_DEQM/DEQM_Capability_Statement_Producer_Server.xlsx",
        # "Documents/Python/Jupyter/MyNotebooks/CapStatement/temp_source_spreadsheets/2022-10-26_DEQM/DEQM_Capability_Statement_Receiver_Server.xlsx",
        # "Documents/Python/Jupyter/MyNotebooks/CapStatement/temp_source_spreadsheets/2022-10-26_DEQM/DEQM_Capability_Statement_Reporter_Client.xlsx",
        #   "Documents/FHIR/Davinci-DEQM/input/resources/source-data/DEQM_Capability_Statement_GIC_Receiver_Server.xlsx",
        #  'C:/Users/Administrator/Downloads/plan-net-server.xlsx',
        'Documents/FHIR/Davinci-ecdx/input/resources-spreadsheet/data-source-client.xlsx',
        'Documents/FHIR/Davinci-ecdx/input/resources-spreadsheet/data-source-server.xlsx',
        'Documents/FHIR/Davinci-ecdx/input/resources-spreadsheet/data-consumer-client.xlsx',
        'Documents/FHIR/Davinci-ecdx/input/resources-spreadsheet/data-consumer-server.xlsx',
        # 'Documents/FHIR/Argo-PL/input/resources-spreadsheet/client.xlsx',
        # 'Documents/FHIR/Argo-PL/input/resources-spreadsheet/server.xlsx',
        ]


# ----------spreadsheet source---------------
from IPython.display import display as Display, HTML, Markdown, Javascript
from ipywidgets import Dropdown
menu = Dropdown(
       options=[my_base + x for x in in_path_list],
       description='Choose Spreadsheet Source file',
       style = {'description_width': 'initial',},
       layout={'width': 'initial'},
        )


menu

Dropdown(description='Choose Spreadsheet Source file', layout=Layout(width='initial'), options=('/Users/ehaas/…

## STEP2:  *CLICK HERE* and then 'Select Run Selected Cell and All Below'  from menu bar to continue"

In [60]:
xls = menu.value
xls

'/Users/ehaas/Documents/FHIR/US-Core/input/resources_spreadsheets/uscore-client.xlsx'

### Import FHIRClient and other libraries

In [61]:
%config IPCompleter.greedy=True

In [62]:
from fhir.resources import construct_fhir_element
from json import dumps, loads
from yaml import load, SafeLoader
from requests import get, post, put
from pathlib import Path
from IPython.display import display as Display, HTML, Markdown, Javascript
import ipywidgets as widgets
from pprint import pprint
from collections import namedtuple
from pandas import *
from datetime import datetime, date, timezone, timedelta
from jinja2 import Environment, FileSystemLoader, select_autoescape
from stringcase import snakecase, titlecase
from commonmark import commonmark
# import markdown
from htmlmin import minify

####  Assign Global Variables

Here is where we assign all the global variables for this example such as the canonical base and project information

In [63]:
fhir_base_url = 'http://hl7.org/fhir/'
f_jurisdiction =  construct_fhir_element('CodeableConcept',{
      "coding" : [
        {
          "system" : "urn:iso:std:iso:3166",
          "code" : "US"
        }
      ]
    })

conf_url = 'http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation'
combo_url = 'http://hl7.org/fhir/StructureDefinition/capabilitystatement-search-parameter-combination'
sp_specials = {'us-core-includeprovenance':'http://hl7.org/fhir/us/core/SearchParameter/us-core-includeprovenance'}  # dict to for SP to get right canonicals, may use spreadsheet or package file in future.

none_list = ['', ' ', 'none', 'n/a', 'N/A', 'N', 'False', None,'!']

sep_list = (',', ';', ' ', ', ', '; ')


timezone_offset = -8.0  # Pacific Standard Time (UTC−08:00)
tzinfo = timezone(timedelta(hours=timezone_offset))
f_now = datetime.now(tzinfo)
f_now
validate_me = False
add_ms_references_summary = False
add_narrative = True #False  # add narrative to resources if not using liquid script or IG publisher default

#### To PascalCase Utility

In [64]:
def kebab_to_pascal(word):
    return ''.join(x.capitalize() for x in word.split('-'))

#### Set Simple Attributes

In [65]:
def set_attr(v=None):
    if v and v not in none_list:
        return v
    else:
        return

#### Set List Attributes

In [66]:
def set_attr_list(v=None):
    if v:
        return [i for i in v.split(",")]
    else:
        return

#### Conformance Extension

In [ ]:
def get_conf(conf='MAY',as_dict=False):
    if as_dict:
        return [construct_fhir_element('Extension',dict(
            url = conf_url,
            valueCode = conf
            )).json()]
    else:
        return [construct_fhir_element('Extension',dict(
            url = conf_url,
            valueCode = conf if conf else "MAY"
            ))]

#### Primitive Conformance Extension

In [ ]:
def get_prim_ext(conf=None):
    if not set(conf).issubset(none_list):
        conf_list = []
        try: # is comma sep string
            conf = conf.split(',')
        except AttributeError: # is list
            pass
        for i in conf:
            if i not in none_list:
                conf_ext = construct_fhir_element('FHIRPrimitiveExtension', dict(
                    extension = get_conf(conf=i),
                    ))
            else:
                conf_ext = None
            conf_list.append(conf_ext)

        return conf_list
    else:
        return

### Addin Extensions

In [ ]:
def get_addin_ext(py_ext, json_ext):
    print(py_ext)
    if json_ext:   # ie not ''
        addin_ext = construct_fhir_element('Extension',loads(json_ext))
        # addin_ext.extension =  get_conf('SHALL') violates invariant   - DONT USE
        print(addin_ext)
        py_ext.append(addin_ext) # add in other extensions
    print(py_ext)
    return py_ext

### validate

In [ ]:
# *********************** validate Resource ********************************

def validate(r):

    #fhir_test_server = 'http://test.fhir.org/r4'
    # fhir_test_server = 'http://hapi.fhir.org/baseR4'
    fhir_test_server = 'http://wildfhir4.aegis.net/fhir4-0-1'

    headers = {
    'Accept':'application/fhir+json',
    'Content-Type':'application/fhir+json',
    }

    # profile = 'http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient' # The official URL for this profile is: http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient

    params = dict(
      # profile = 'http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient' # The official URL for this profile is: http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient
        )

    #   r = requests.post('https://httpbin.org/post', data = {'key':'value'})
    r = post(f'{fhir_test_server}/CapabilityStatement/$validate', params = params, headers = headers, data = r.json().encode('utf-8'))
    # return r.status_code
    # view  output
    # return (r.json()["text"]["div"])
    return r

### Get Cap Statement input data

function to convert to dataframe series to namedtuple for easy peasy dot notation use.

#### first the config data

In [71]:
df = read_excel(xls,'config',na_filter = False,index_col=0)  # use the index_col = 0 for setting the first rwo as the index

df

                                                             Value
Name
source                  /Users/ehaas/Documents/FHIR/US-Core/input/
packagepath       http://build.fhir.org/ig/HL7/US-Core/package.tgz
pre                                                        US-Core
canon                                 http://hl7.org/fhir/us/core/
publisher                 HL7 International - Cross-Group Projects
publishersystem                                                url
publishervalue           http://www.hl7.org/Special/committees/cgp
suppress_may_sps                                              True

#### assign globals e.g. publisher parameter etc...

In [72]:
#df.[Column].[row] to get a value df.loc[[row],[Column]] or df.at[[column],[col]] works too
df.Value.source #, df.loc['source','Value'], df.at['source' ,'Value']

'/Users/ehaas/Documents/FHIR/US-Core/input/'

In [73]:

ig_source_path = df.Value.source
ig_package_tar_path =  df.Value.packagepath  # e.g. : https://build.fhir.org/ig/HL7/davinci-alerts/package.tgz  consider using the ig resource instead since this may out of synch with latest changes

# --------- ig specific variable -------------------
# get these from the ig.yaml I create in the input/data folder ---
# --- !!! need to successfully run Sushi to build the IG resource first!!! ---
ig_resource_path = Path(ig_source_path) / "data" / "ig.yml"  #e.g.: /Users/ehaas/Documents/FHIR/US-Core/temp/pages/_data/resources.json
ig_resource = load(ig_resource_path.read_text(), Loader=SafeLoader)
ig_version = ig_resource['version']
canon = ig_resource['url'].split('ImplementationGuide')[0]
publisher = ig_resource['publisher']
pre = df.Value.pre  # for Titles


# canon = df.Value.canon # don't forget the slash  - fix using os.join or path
#
publisher = df.Value.publisher
#
publisher_endpoint = dict(
                    system = ig_resource['contact'][0]['telecom'][0]['system'],
                    value = ig_resource['contact'][0]['telecom'][0]['value'],
                  )


print(f'''ig_source_path = {ig_source_path}
ig_package_tar_path  = {ig_package_tar_path}
ig_resource_path = {ig_resource_path}
ig_version = {ig_version}
canonical = {canon}
pre = {pre}
publisher = {publisher}
publisher_endpoint = {publisher_endpoint}''')

ig_source_path = /Users/ehaas/Documents/FHIR/US-Core/input/
ig_package_tar_path  = http://build.fhir.org/ig/HL7/US-Core/package.tgz
ig_resource_path = /Users/ehaas/Documents/FHIR/US-Core/input/data/ig.yml
ig_version = 9.0.0-ballot
canonical = http://hl7.org/fhir/us/core/
pre = US-Core
publisher = HL7 International - Cross-Group Projects
publisher_endpoint = {'system': 'url', 'value': 'http://www.hl7.org/Special/committees/cgp'}

#### Get the meta sheet

In [74]:
4

4

In [75]:
df = read_excel(xls,'meta',na_filter = False)

df

             Element                                              Value
0                 id                                     us-core-client
1            version                                       9.0.0-ballot
2        fhirVersion                                              4.0.1
3        description  This Section describes the expected capabiliti...
4               mode                                             client
5      documentation  The US Core Client **SHALL**:\n\n1. Support fe...
6           security  1. See the [General Security Considerations](s...
7             format                                           json,xml
8        format_conf                                       SHALL,SHOULD
9        patchFormat                        application/json-patch+json
10  patchFormat_conf                                             SHOULD

#### Create NamedTuple from df to use dot notation

In [ ]:
d = dict(zip(df.Element, df.Value))
meta = namedtuple("Meta", d.keys())(*d.values())

meta.id

'us-core-client'


### Create CS instance

In [77]:
cs = construct_fhir_element('CapabilityStatement',dict(
id = meta.id,
url = f'{canon}CapabilityStatement/{meta.id}',
version = meta.version,
name = f'{kebab_to_pascal(meta.id)}CapabilityStatement',
title = f'{titlecase(meta.id).replace("Us ", "US ")} CapabilityStatement',
status = 'active',
experimental = False,
date = f_now, # as FHIRDate
publisher = publisher,
contact = [construct_fhir_element('ContactDetail', {"telecom" : [ publisher_endpoint ] })],
description = meta.description,
jurisdiction = [f_jurisdiction],
kind = 'requirements',
fhirVersion = meta.fhirVersion,
format = set_attr_list(meta.format),
format__ext = get_prim_ext(meta.format_conf),
patchFormat = set_attr_list(meta.patchFormat),
patchFormat__ext = get_prim_ext(meta.patchFormat_conf),
))

print(cs.json(indent=2))

{
  "resourceType": "CapabilityStatement",
  "id": "us-core-client",
  "url": "http://hl7.org/fhir/us/core/CapabilityStatement/us-core-client",
  "version": "9.0.0-ballot",
  "name": "UsCoreClientCapabilityStatement",
  "title": "US Core Client CapabilityStatement",
  "status": "active",
  "experimental": false,
  "date": "2025-12-19T19:16:08.871976-08:00",
  "publisher": "HL7 International - Cross-Group Projects",
  "contact": [
    {
      "telecom": [
        {
          "system": "url",
          "value": "http://www.hl7.org/Special/committees/cgp"
        }
      ]
    }
  ],
  "description": "This Section describes the expected capabilities of the US Core Client which is responsible for creating and initiating the queries for information about an individual patient. The complete list of FHIR profiles, RESTful operations, and search parameters supported by US Core Servers are defined in the [Conformance Requirements for Server](CapabilityStatement-us-core-server.html). US Core Clients have the option of choosing from this list to access necessary data based on their local use cases and other contextual requirements.",
  "jurisdiction": [
    {
      "coding": [
        {
          "system": "urn:iso:std:iso:3166",
          "code": "US"
        }
      ]
    }
  ],
  "kind": "requirements",
  "fhirVersion": "4.0.1",
  "format": [
    "json",
    "xml"
  ],
  "_format": [
    {
      "extension": [
        {
          "url": "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation",
          "valueCode": "SHALL"
        }
      ]
    },
    {
      "extension": [
        {
          "url": "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation",
          "valueCode": "SHOULD"
        }
      ]
    }
  ],
  "patchFormat": [
    "application/json-patch+json"
  ],
  "_patchFormat": [
    {
      "extension": [
        {
          "url": "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation",
          "valueCode": "SHOULD"
        }
      ]
    }
  ]
}

### Add in Rest

In [78]:
def get_sys_op():
    op_list = []
    df_op = read_excel(xls,'ops',na_filter = False)
    for i in df_op.itertuples(index=True):
        if i.type == 'system':
            op = construct_fhir_element('CapabilityStatementRestResourceOperation', dict(
            #op = CS.CapabilityStatementRestResourceOperation()
            name = i.name,
            definition = i.definition,
            documentation = i.documentation if i.documentation not in none_list else None,
            extension = get_conf(i.conf),
            ))
            op_list.append(op.json())
    return op_list if op_list else None


def get_rest_ints():
    ri_list = []
    df_ri = read_excel(xls,'rest_interactions',na_filter = False)
    for i in df_ri.itertuples(index=True):
        ri = construct_fhir_element('CapabilityStatementRestInteraction', dict(
        code = i.code,
        documentation = i.doc if i.doc not in none_list else None,
        extension = get_conf(i.conf),
        ))
        print(ri.json(indent=2))
        ri_list.append(ri.json())
    return ri_list  if ri_list else None

rest = construct_fhir_element('CapabilityStatementRest',(dict(
    mode = meta.mode,
    documentation = meta.documentation,
    security = dict(
        description = meta.security
        ) if meta.security else None,
    interaction = get_rest_ints(),
    operation = get_sys_op()
    )))

cs.rest = [rest]

print(cs.json(indent=2))

{
  "extension": [
    {
      "url": "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation",
      "valueCode": "MAY"
    }
  ],
  "code": "transaction"
}
{
  "extension": [
    {
      "url": "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation",
      "valueCode": "MAY"
    }
  ],
  "code": "batch"
}
{
  "extension": [
    {
      "url": "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation",
      "valueCode": "MAY"
    }
  ],
  "code": "search-system"
}
{
  "extension": [
    {
      "url": "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation",
      "valueCode": "MAY"
    }
  ],
  "code": "history-system"
}
{
  "resourceType": "CapabilityStatement",
  "id": "us-core-client",
  "url": "http://hl7.org/fhir/us/core/CapabilityStatement/us-core-client",
  "version": "9.0.0-ballot",
  "name": "UsCoreClientCapabilityStatement",
  "title": "US Core Client CapabilityStatement",
  "status": "active",
  "experimental": false,
  "date": "2025-12-19T19:16:08.871976-08:00",
  "publisher": "HL7 International - Cross-Group Projects",
  "contact": [
    {
      "telecom": [
        {
          "system": "url",
          "value": "http://www.hl7.org/Special/committees/cgp"
        }
      ]
    }
  ],
  "description": "This Section describes the expected capabilities of the US Core Client which is responsible for creating and initiating the queries for information about an individual patient. The complete list of FHIR profiles, RESTful operations, and search parameters supported by US Core Servers are defined in the [Conformance Requirements for Server](CapabilityStatement-us-core-server.html). US Core Clients have the option of choosing from this list to access necessary data based on their local use cases and other contextual requirements.",
  "jurisdiction": [
    {
      "coding": [
        {
          "system": "urn:iso:std:iso:3166",
          "code": "US"
        }
      ]
    }
  ],
  "kind": "requirements",
  "fhirVersion": "4.0.1",
  "format": [
    "json",
    "xml"
  ],
  "_format": [
    {
      "extension": [
        {
          "url": "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation",
          "valueCode": "SHALL"
        }
      ]
    },
    {
      "extension": [
        {
          "url": "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation",
          "valueCode": "SHOULD"
        }
      ]
    }
  ],
  "patchFormat": [
    "application/json-patch+json"
  ],
  "_patchFormat": [
    {
      "extension": [
        {
          "url": "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation",
          "valueCode": "SHOULD"
        }
      ]
    }
  ],
  "rest": [
    {
      "mode": "client",
      "documentation": "The US Core Client **SHALL**:\n\n1. Support fetching and querying of one or more US Core profile(s), using the supported RESTful interactions and search parameters declared in the US Core Server CapabilityStatement.\n1. Follow the requirements documented in the [General Requirements](general-requirements.html) and [Must Support](must-support.html) pages\n\n**NOTE**: US Core SearchParameters referenced in this CapabilityStatement that are derived from standard FHIR SearchParameters are only defined to document Server and Client expectations. They specify additional expectations for the following SearchParameter elements:\n\n- `multipleAnd`\n- `multipleOr`\n- `comparator`\n- `modifier`\n- `chain`\n\nThey **SHALL NOT** be interpreted as search parameters for search. Servers and Clients **SHOULD** use the standard FHIR SearchParameters.",
      "security": {
        "description": "1. See the [General Security Considerations](security.html) section for requirements and recommendations."
      },
      "interaction": [
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation",
              "valueCode": "MAY"
            }
          ],
          "code": "transaction"
        },
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation",
              "valueCode": "MAY"
            }
          ],
          "code": "batch"
        },
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation",
              "valueCode": "MAY"
            }
          ],
          "code": "search-system"
        },
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation",
              "valueCode": "MAY"
            }
          ],
          "code": "history-system"
        }
      ]
    }
  ]
}

### Add in IG, and Capstatements and their conformance

In [79]:
df_igs = read_excel(xls,'igs',na_filter = False)
cs.implementationGuide = set_attr([ig.canonical for ig in df_igs.itertuples(index=True) if '!' not in ig.name])
#print([ig.conformance for ig in df_igs.itertuples(index=True) if ig.imports not in none_list])
cs.implementationGuide__ext = get_prim_ext([ig.conformance for ig in df_igs.itertuples(index=True) if '!' not in ig.name])

df_capstatements = read_excel(xls,'capstatements',na_filter = False)
cs.imports = set_attr([ig.canonical for ig in df_capstatements.itertuples(index=True) if ig.imports not in none_list])
cs.imports__ext = get_prim_ext([ig.conformance for ig in df_capstatements.itertuples(index=True) if ig.imports not in none_list])
cs.instantiates = set_attr([ig.canonical for ig in df_capstatements.itertuples(index=True) if ig.instantiates not in none_list])
cs.instantiates__ext = get_prim_ext([ig.conformance for ig in df_capstatements.itertuples(index=True) if ig.instantiates not in none_list])

print(cs.json(indent=2))

{
  "resourceType": "CapabilityStatement",
  "id": "us-core-client",
  "url": "http://hl7.org/fhir/us/core/CapabilityStatement/us-core-client",
  "version": "9.0.0-ballot",
  "name": "UsCoreClientCapabilityStatement",
  "title": "US Core Client CapabilityStatement",
  "status": "active",
  "experimental": false,
  "date": "2025-12-19T19:16:08.871976-08:00",
  "publisher": "HL7 International - Cross-Group Projects",
  "contact": [
    {
      "telecom": [
        {
          "system": "url",
          "value": "http://www.hl7.org/Special/committees/cgp"
        }
      ]
    }
  ],
  "description": "This Section describes the expected capabilities of the US Core Client which is responsible for creating and initiating the queries for information about an individual patient. The complete list of FHIR profiles, RESTful operations, and search parameters supported by US Core Servers are defined in the [Conformance Requirements for Server](CapabilityStatement-us-core-server.html). US Core Clients have the option of choosing from this list to access necessary data based on their local use cases and other contextual requirements.",
  "jurisdiction": [
    {
      "coding": [
        {
          "system": "urn:iso:std:iso:3166",
          "code": "US"
        }
      ]
    }
  ],
  "kind": "requirements",
  "fhirVersion": "4.0.1",
  "format": [
    "json",
    "xml"
  ],
  "_format": [
    {
      "extension": [
        {
          "url": "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation",
          "valueCode": "SHALL"
        }
      ]
    },
    {
      "extension": [
        {
          "url": "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation",
          "valueCode": "SHOULD"
        }
      ]
    }
  ],
  "patchFormat": [
    "application/json-patch+json"
  ],
  "_patchFormat": [
    {
      "extension": [
        {
          "url": "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation",
          "valueCode": "SHOULD"
        }
      ]
    }
  ],
  "implementationGuide": [
    "http://hl7.org/fhir/smart-app-launch/ImplementationGuide/hl7.fhir.uv.smart-app-launch"
  ],
  "_implementationGuide": [
    {
      "extension": [
        {
          "url": "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation",
          "valueCode": "SHOULD"
        }
      ]
    }
  ],
  "rest": [
    {
      "mode": "client",
      "documentation": "The US Core Client **SHALL**:\n\n1. Support fetching and querying of one or more US Core profile(s), using the supported RESTful interactions and search parameters declared in the US Core Server CapabilityStatement.\n1. Follow the requirements documented in the [General Requirements](general-requirements.html) and [Must Support](must-support.html) pages\n\n**NOTE**: US Core SearchParameters referenced in this CapabilityStatement that are derived from standard FHIR SearchParameters are only defined to document Server and Client expectations. They specify additional expectations for the following SearchParameter elements:\n\n- `multipleAnd`\n- `multipleOr`\n- `comparator`\n- `modifier`\n- `chain`\n\nThey **SHALL NOT** be interpreted as search parameters for search. Servers and Clients **SHOULD** use the standard FHIR SearchParameters.",
      "security": {
        "description": "1. See the [General Security Considerations](security.html) section for requirements and recommendations."
      },
      "interaction": [
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation",
              "valueCode": "MAY"
            }
          ],
          "code": "transaction"
        },
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation",
              "valueCode": "MAY"
            }
          ],
          "code": "batch"
        },
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation",
              "valueCode": "MAY"
            }
          ],
          "code": "search-system"
        },
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation",
              "valueCode": "MAY"
            }
          ],
          "code": "history-system"
        }
      ]
    }
  ]
}

### add Resources

- read sheets for resource attributes, interaction attributes,  search attributes, profiles, and combo search parameters

In [80]:
df_resources = read_excel(xls,'resources',na_filter = False)
df_resources = df_resources[df_resources.type.str[0] != '!']
df_resources

,type,conformance,documentation,profile,profile_conf,versioning,versioning_conf,readHistory,readHistory_conf,updateCreate,...,conditionalUpdate,conditionalUpdate_conf,conditionalDelete,conditionalDelete_conf,referencePolicy,referencePolicy_conf,include_conf,include,revinclude,revinclude_conf
0,AllergyIntolerance,SHOULD,,,,,,,,,...,,,,,,,,,Provenance:target,SHOULD
1,CarePlan,SHOULD,* Additional considerations for systems aligni...,,,,,,,,...,,,,,,,,,Provenance:target,SHOULD
2,CareTeam,SHOULD,"* In order to access care team member's names,...",,,,,,,,...,,,,,,,"SHOULD,SHOULD,SHOULD,SHOULD","CareTeam:participant:PractitionerRole,CareTeam...",Provenance:target,SHOULD
3,Condition,SHOULD,* For Encounter Diagnosis use the *US Core Con...,,,,,,,,...,,,,,,,,,Provenance:target,SHOULD
4,Coverage,SHOULD,,,,,,,,,...,,,,,,,,,Provenance:target,SHOULD
5,Device,SHOULD,* Medical devices with UDI information **SHALL...,,,,,,,,...,,,,,,,,,Provenance:target,SHOULD
6,DiagnosticReport,SHOULD,* For laboratory result reports use the *US Co...,,,,,,,,...,,,,,,,,,Provenance:target,SHOULD
7,DocumentReference,SHOULD,* For Advance Directive Information (ADI) docu...,,,,,,,,...,,,,,,,,,Provenance:target,SHOULD
8,Encounter,SHOULD,* The Encounter resource can represent a reaso...,,,,,,,,...,,,,,,,,,Provenance:target,SHOULD
9,Endpoint,SHOULD,The Media Resource is a Must Support reference...,,,,,,,,...,,,,,,,,,,
10,FamilyMemberHistory,SHOULD,,,,,,,,,...,,,,,,,,,Provenance:target,SHOULD
11,Goal,SHOULD,* Although both `Goal.startDate` and `Goal.tar...,,,,,,,,...,,,,,,,,,Provenance:target,SHOULD
12,HealthcareService,MAY,The HealthcareService Resource is a referenced...,,,,,,,,...,,,,,,,,,,
13,Immunization,SHOULD,* Based upon the ASTP U.S. Core Data for Inter...,,,,,,,,...,,,,,,,,,Provenance:target,SHOULD
14,Location,SHOULD,* Systems **SHOULD** follow the Project US@ Te...,,,,,,,,...,,,,,,,,,,
15,Media,SHOULD,The Media Resource is a Must Support reference...,,,,,,,,...,,,,,,,,,,
16,Medication,SHOULD,* The MedicationRequest resource can represen...,,,,,,,,...,,,,,,,,,,
17,MedicationRequest,SHOULD,* This Profile can represent a medication usin...,,,,,,,,...,,,,,,,SHOULD,MedicationRequest:medication,Provenance:target,SHOULD
18,MedicationDispense,SHOULD,* This Profile can represent a medication usin...,,,,,,,,...,,,,,,,SHOULD,MedicationDispense:medication,Provenance:target,SHOULD
20,Observation,SHOULD,* Systems **SHOULD** support `Observation.effe...,,,,,,,,...,,,,,,,,,Provenance:target,SHOULD
21,Organization,SHOULD,* Systems **SHALL** support National Provider ...,,,,,,,,...,,,,,,,,,,
22,Patient,SHOULD,* The Patient's Social Security Numbers **SHOU...,,,,,,,,...,,,,,,,,,Provenance:target,SHOULD
23,Practitioner,SHOULD,* Servers that support only US Core Practition...,,,,,,,,...,,,,,,,,,,
24,PractitionerRole,SHOULD,"* Due to implementer feedback, some US Core Pr...",,,,,,,,...,,,,,,,"SHOULD,SHOULD","PractitionerRole:endpoint,PractitionerRole:pra...",,
25,Procedure,SHOULD,"* Procedure codes can be taken from SNOMED-CT,...",,,,,,,,...,,,,,,,,,Provenance:target,SHOULD
26,Provenance,SHOULD,* The US Core Provenance resource **SHALL** be...,,,,,,,,...,,,,,,,,,,
27,Questionnaire,SHOULD,* US Core defines two ways to represent the qu...,,,,,,,,...,,,,,,,,,,
28,QuestionnaireResponse,SHOULD,* US Core defines two ways to represent the qu...,,,,,,,,...,,,,,,,,,Provenance:target,SHOULD
29,RelatedPerson,SHOULD,* Systems **SHOULD** follow the Project US@ Te...,,,,,,,,...,,,,,,,,,Provenance:target,SHOULD
30,ServiceRequest,SHOULD,* The Must Support `ServiceRequest.category` i...,,,,,,,,...,,,,,,,,,Provenance:target,SHOULD
31,Specimen,SHOULD,* Although both `Specimen.identifier` and `Spe...,,,,,,,,...,,,,,,,,,,
32,ValueSet,SHOULD,,,,,,,,,...,,,,,,,,,,

In [81]:
df_profiles = read_excel(xls,'profiles',na_filter = False)  #df1 = df[df.Hostname.str[0] != "abc"]
df_profiles = df_profiles[df_profiles.Profile.str[0] != '!']
df_profiles

,Profile,Name,url,Conformance,Type
0,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core AllergyIntolerance Profile,,SHALL,AllergyIntolerance
1,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core CarePlan Profile,,SHALL,CarePlan
2,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core CareTeam Profile,,SHALL,CareTeam
3,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core Condition Encounter Diagnosis Profile,,SHALL,Condition
4,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core Condition Problems and Health Concerns...,,SHALL,Condition
5,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core Coverage Profile,,SHALL,Coverage
6,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core Device Profile,,SHALL,Device
7,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core DiagnosticReport Profile for Report an...,,SHALL,DiagnosticReport
8,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core DiagnosticReport Profile for Laborator...,,SHALL,DiagnosticReport
9,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core DocumentReference Profile,,SHALL,DocumentReference
10,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core ADI DocumentReference Profile,,SHALL,DocumentReference
11,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core Encounter Profile,,SHALL,Encounter
18,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core FamilyMemberHistory Profile,,SHALL,FamilyMemberHistory
19,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core Goal Profile,,SHALL,Goal
20,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core Immunization Profile,,SHALL,Immunization
21,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core Location Profile,,SHALL,Location
22,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core Medication Profile,,SHALL,Medication
23,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core MedicationRequest Profile,,SHALL,MedicationRequest
24,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core MedicationDispense Profile,,SHALL,MedicationDispense
25,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core Observation ADI Documentation Profile,,SHALL,Observation
26,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core Laboratory Result Observation Profile,,SHALL,Observation
27,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core Observation Pregnancy Status Profile,,SHALL,Observation
28,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core Observation Pregnancy Intent Profile,,SHALL,Observation
29,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core Observation Occupation Profile,,SHALL,Observation
31,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core Respiratory Rate Profile,,SHALL,Observation
32,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core Simple Observation Profile,,SHALL,Observation
33,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core Treatment Intervention Preference Profile,,SHALL,Observation
34,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core Care Experience Preference Profile,,SHALL,Observation
35,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core Heart Rate Profile,,SHALL,Observation
36,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core Body Temperature Profile,,SHALL,Observation
37,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core Pediatric Weight for Height Observatio...,,SHALL,Observation
38,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core Pulse Oximetry Profile,,SHALL,Observation
39,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core Smoking Status Observation Profile,,SHALL,Observation
40,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core Observation Sexual Orientation Profile,,MAY,Observation
41,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core Head Circumference Profile,,SHALL,Observation
42,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core Body Height Profile,,SHALL,Observation
43,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core BMI Profile,,SHALL,Observation
44,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core Observation Screening Assessment Profile,,SHALL,Observation
45,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core Average Blood Pressure Profile,,SHALL,Observation
46,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core Blood Pressure Profile,,SHALL,Observation
48,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core Observation Clinical Result Profile,,SHALL,Observation
49,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core Pediatric BMI for Age Observation Profile,,SHALL,Observation
50,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core Pediatric Head Occipital Frontal Circu...,,SHALL,Observation
51,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core Body Weight Profile,,SHALL,Observation
52,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core Vital Signs Profile,,SHALL,Observation
53,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core Organization Profile,,SHALL,Organization
54,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core Patient Profile,,SHALL,Patient
55,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core Practitioner Profile,,SHALL,Practitioner
56,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core PractitionerRole Profile,,SHALL,PractitionerRole
57,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core Procedure Profile,,SHALL,Procedure
58,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core Provenance Profile,,SHALL,Provenance
59,http://hl7.org/fhir/uv/sdc/StructureDefinition...,SDC Base Questionnaire Profile,,SHALL,Questionnaire
60,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core QuestionnaireResponse Profile,,SHALL,QuestionnaireResponse
61,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core RelatedPerson Profile,,SHALL,RelatedPerson
62,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core PMO ServiceRequest Profile,,SHALL,ServiceRequest
63,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core ServiceRequest Profile,,SHALL,ServiceRequest
64,http://hl7.org/fhir/us/core/StructureDefinitio...,US Core Specimen Profile,,SHALL,Specimen

In [82]:
df_i = read_excel(xls,'interactions',na_filter = False)
df_sp = read_excel(xls,'sps',na_filter = False)
df_combos = read_excel(xls,'sp_combos',na_filter = False)
df_op = read_excel(xls,'ops',na_filter = False)


def get_i(type):
    int_list = []
    for i in df_i.itertuples(index=True):
        #print(i.code, getattr(i,f'conf_{type}'))
        if getattr(i,f'conf_{type}') not in none_list:
            try:
                documentation = getattr(i,f'doc_{type}') if getattr(i,f'doc_{type}') not in none_list else None
            except AttributeError:
                documentation = None
            int  = construct_fhir_element('CapabilityStatementRestResourceInteraction', dict(
            code = i.code,
            documentation = documentation,
            extension = get_conf(getattr(i,f'conf_{type}')),
            ))
            int_list.append(int.json()),
    return int_list if int_list else None


def get_sp(r_type):
    sp_list = []
    for i in df_sp.itertuples(index=True):
        if i.base == r_type:
            # TODO need to fix this to reference the package file to reconcile definition to names
            if i.code in sp_specials: #special case temp fix for us-core
                definition = sp_specials[i.code]
            elif i.update == 'Y' or i.exists =='N':
                definition = f'{canon}SearchParameter/{pre.lower()}-{i.base.lower()}-{i.code.lower().replace("_","")}'
            elif i.code.startswith('_'): #common sp
                definition = f'{fhir_base_url}SearchParameter/{i.code.replace("_","Resource-")}'
            else:  # use base definition
                definition = f'{fhir_base_url}SearchParameter/{i.base}-{i.code}'
            # print(definition)

            sp  = construct_fhir_element('CapabilityStatementRestResourceSearchParam', dict(
            name = i.code,
            definition = definition,
            documentation = i.documentation if i.documentation not in none_list else None,
            type = i.type,
            extension = get_conf(i.base_conf),
            ))
            #print(sp.json())
            sp_list.append(sp.json())
    return sp_list if sp_list else None


def get_combo_ext(r_type,combos):
    x_list = []
    for combo in combos:
        # convert to extension
        combo_ext = construct_fhir_element('Extension', dict (
        url = combo_url,
        extension=get_conf(combo[1]),
        ))
        for param in combo[0].split(','):
            req_combo = construct_fhir_element('Extension', dict (
                    url = 'required',
                    valueString = param,   #http://hl7.org/fhir/us/core/SearchParameter/us-core-patient-family
                ))
            combo_ext.extension.append(req_combo)
        x_list.append(combo_ext)
        # print(x_list)
    return x_list

def get_op(r_type):
    op_list = []
    for i in df_op.itertuples(index=True):
         if i.type == r_type:
            op = construct_fhir_element('CapabilityStatementRestResourceOperation', dict(
            name = i.name,
            definition = i.definition,
            documentation = i.documentation if i.documentation not in none_list else None,
            extension = get_conf(i.conf),
            ))
            try:
                op.extension =  get_addin_ext(op.extension, i.ext)
            except AttributeError:
                print("---- no addin extensions found-----")
            op_list.append(op.json())
    return op_list if op_list else None


rest.resource =  []
for r in df_resources.itertuples(index=True):
  # if r.type == "Observation":
    # print(r.type, r.conformance, r.readHistory
    supported_profile = [f'{p.Profile}{f"|{cs.version}" if canon in p.Profile else ""}' for p in df_profiles.itertuples(index=True) if p.Type == r.type]
    supported_profile_name = [p.Name for p in df_profiles.itertuples(index=True) if p.Type == r.type]
    supported_profile_rel_link = [f'StructureDefinition-{p.Profile.split("/")[-1]}.html' for p in df_profiles.itertuples(index=True) if p.Type == r.type]
    supported_profile_ext = get_prim_ext([p.Conformance for p in df_profiles.itertuples(index=True) if p.Type == r.type])

    print(r.type, supported_profile)
    # pprint(supported_profile_name)
    # pprint(supported_profile_rel_link)
    # pprint(supported_profile_ext)
    # supported_profile_ref = construct_fhir_element('Extension',{'url': 'http://hl7.org/fhir/StructureDefinition/artifact-reference', 'valueReference': {'reference': 'StructureDefinition-us-core-allergyintolerance.html', 'display': 'US Core AllergyIntolerance Profile'}})
    # supported_profile_ext[0].extension.append(supported_profile_ref)
    # pprint(supported_profile_ext)
    try:
      for i,ext in enumerate(supported_profile_ext):
          pprint(supported_profile[i])
          print(i, ext)
          supported_profile_ref = construct_fhir_element('Extension',{'url': 'http://hl7.org/fhir/StructureDefinition/artifact-reference', 'valueReference': {'reference': supported_profile_rel_link[i], 'display': supported_profile_name[i]}})
          ext.extension.append(supported_profile_ref)
          # print(i, ext)
          # print('='*80)
    except TypeError:
        print(f'No Profiles for " {r.type}"')


    res = construct_fhir_element('CapabilityStatementRestResource', dict(
        type = r.type,
        documentation = set_attr(r.documentation),
        versioning = set_attr(r.versioning),
        readHistory = set_attr(r.readHistory),
        updateCreate = set_attr(r.updateCreate),
        conditionalCreate = set_attr(r.conditionalCreate),
        conditionalRead = set_attr(r.conditionalRead),
        conditionalUpdate = set_attr(r.conditionalUpdate),
        conditionalDelete = set_attr(r.conditionalDelete),
        referencePolicy = set_attr_list(r.referencePolicy),
        referencePolicy__ext = get_prim_ext(r.referencePolicy_conf),
        searchInclude = set_attr_list(r.include),
        searchInclude__ext = get_prim_ext(r.include_conf),
        searchRevInclude = set_attr_list(r.revinclude),
        searchRevInclude__ext = get_prim_ext(r.revinclude_conf),
        interaction = get_i(r.type),
        searchParam = get_sp(r.type),
        operation = get_op(r.type),
        profile = set_attr(r.profile),
        supportedProfile = supported_profile if supported_profile else None,
        supportedProfile__ext = supported_profile_ext
        )
    )
    res.extension = get_conf(r.conformance)
    combos = {(i.combo,i.combo_conf) for i in df_combos.itertuples(index=True) if i.base == r.type}
    res.extension = res.extension + get_combo_ext(r.type,combos) # convert list to  lst of combo extension
    rest.resource.append(res)

rest.resource =  sorted(rest.resource,key = lambda x: x.type)  # sort resources
cs.rest = [rest]

# print(cs.json(indent=2))
### Validate

AllergyIntolerance ['http://hl7.org/fhir/us/core/StructureDefinition/us-core-allergyintolerance|9.0.0-ballot']
'http://hl7.org/fhir/us/core/StructureDefinition/us-core-allergyintolerance|9.0.0-ballot'
0 resource_type='FHIRPrimitiveExtension' fhir_comments=None id=None extension=[Extension(resource_type='Extension', fhir_comments=None, extension=None, id=None, url='http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation', valueAddress=None, valueAge=None, valueAnnotation=None, valueAttachment=None, valueBase64Binary=None, valueBoolean=None, valueCanonical=None, valueCode='SHALL', valueCodeableConcept=None, valueCoding=None, valueContactDetail=None, valueContactPoint=None, valueContributor=None, valueCount=None, valueDataRequirement=None, valueDate=None, valueDateTime=None, valueDecimal=None, valueDistance=None, valueDosage=None, valueDuration=None, valueExpression=None, valueHumanName=None, valueId=None, valueIdentifier=None, valueInstant=None, valueInteger=None, valueMarkdown=None, valueMeta=None, valueMoney=None, valueOid=None, valueParameterDefinition=None, valuePeriod=None, valuePositiveInt=None, valueQuantity=None, valueRange=None, valueRatio=None, valueReference=None, valueRelatedArtifact=None, valueSampledData=None, valueSignature=None, valueString=None, valueTime=None, valueTiming=None, valueTriggerDefinition=None, valueUnsignedInt=None, valueUri=None, valueUrl=None, valueUsageContext=None, valueUuid=None)]
CarePlan ['http://hl7.org/fhir/us/core/StructureDefinition/us-core-careplan|9.0.0-ballot']
'http://hl7.org/fhir/us/core/StructureDefinition/us-core-careplan|9.0.0-ballot'
0 resource_type='FHIRPrimitiveExtension' fhir_comments=None id=None extension=[Extension(resource_type='Extension', fhir_comments=None, extension=None, id=None, url='http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation', valueAddress=None, valueAge=None, valueAnnotation=None, valueAttachment=None, valueBase64Binary=None, valueBoolean=None, valueCanonical=None, valueCode='SHALL', valueCodeableConcept=None, valueCoding=None, valueContactDetail=None, valueContactPoint=None, valueContributor=None, valueCount=None, valueDataRequirement=None, valueDate=None, valueDateTime=None, valueDecimal=None, valueDistance=None, valueDosage=None, valueDuration=None, valueExpression=None, valueHumanName=None, valueId=None, valueIdentifier=None, valueInstant=None, valueInteger=None, valueMarkdown=None, valueMeta=None, valueMoney=None, valueOid=None, valueParameterDefinition=None, valuePeriod=None, valuePositiveInt=None, valueQuantity=None, valueRange=None, valueRatio=None, valueReference=None, valueRelatedArtifact=None, valueSampledData=None, valueSignature=None, valueString=None, valueTime=None, valueTiming=None, valueTriggerDefinition=None, valueUnsignedInt=None, valueUri=None, valueUrl=None, valueUsageContext=None, valueUuid=None)]
CareTeam ['http://hl7.org/fhir/us/core/StructureDefinition/us-core-careteam|9.0.0-ballot']
'http://hl7.org/fhir/us/core/StructureDefinition/us-core-careteam|9.0.0-ballot'
0 resource_type='FHIRPrimitiveExtension' fhir_comments=None id=None extension=[Extension(resource_type='Extension', fhir_comments=None, extension=None, id=None, url='http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation', valueAddress=None, valueAge=None, valueAnnotation=None, valueAttachment=None, valueBase64Binary=None, valueBoolean=None, valueCanonical=None, valueCode='SHALL', valueCodeableConcept=None, valueCoding=None, valueContactDetail=None, valueContactPoint=None, valueContributor=None, valueCount=None, valueDataRequirement=None, valueDate=None, valueDateTime=None, valueDecimal=None, valueDistance=None, valueDosage=None, valueDuration=None, valueExpression=None, valueHumanName=None, valueId=None, valueIdentifier=None, valueInstant=None, valueInteger=None, valueMarkdown=None, valueMeta=None, valueMoney=None, valueOid=None, valueParameterDefinition=None, valuePeriod=None, valuePositiveInt=None, valueQuantity=None, valueRange=None, valueRatio=None, valueReference=None, valueRelatedArtifact=None, valueSampledData=None, valueSignature=None, valueString=None, valueTime=None, valueTiming=None, valueTriggerDefinition=None, valueUnsignedInt=None, valueUri=None, valueUrl=None, valueUsageContext=None, valueUuid=None)]
Condition ['http://hl7.org/fhir/us/core/StructureDefinition/us-core-condition-encounter-diagnosis|9.0.0-ballot', 'http://hl7.org/fhir/us/core/StructureDefinition/us-core-condition-problems-health-concerns|9.0.0-ballot']
'http://hl7.org/fhir/us/core/StructureDefinition/us-core-condition-encounter-diagnosis|9.0.0-ballot'
0 resource_type='FHIRPrimitiveExtension' fhir_comments=None id=None extension=[Extension(resource_type='Extension', fhir_comments=None, extension=None, id=None, url='http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation', valueAddress=None, valueAge=None, valueAnnotation=None, valueAttachment=None, valueBase64Binary=None, valueBoolean=None, valueCanonical=None, valueCode='SHALL', valueCodeableConcept=None, valueCoding=None, valueContactDetail=None, valueContactPoint=None, valueContributor=None, valueCount=None, valueDataRequirement=None, valueDate=None, valueDateTime=None, valueDecimal=None, valueDistance=None, valueDosage=None, valueDuration=None, valueExpression=None, valueHumanName=None, valueId=None, valueIdentifier=None, valueInstant=None, valueInteger=None, valueMarkdown=None, valueMeta=None, valueMoney=None, valueOid=None, valueParameterDefinition=None, valuePeriod=None, valuePositiveInt=None, valueQuantity=None, valueRange=None, valueRatio=None, valueReference=None, valueRelatedArtifact=None, valueSampledData=None, valueSignature=None, valueString=None, valueTime=None, valueTiming=None, valueTriggerDefinition=None, valueUnsignedInt=None, valueUri=None, valueUrl=None, valueUsageContext=None, valueUuid=None)]
'http://hl7.org/fhir/us/core/StructureDefinition/us-core-condition-problems-health-concerns|9.0.0-ballot'
1 resource_type='FHIRPrimitiveExtension' fhir_comments=None id=None extension=[Extension(resource_type='Extension', fhir_comments=None, extension=None, id=None, url='http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation', valueAddress=None, valueAge=None, valueAnnotation=None, valueAttachment=None, valueBase64Binary=None, valueBoolean=None, valueCanonical=None, valueCode='SHALL', valueCodeableConcept=None, valueCoding=None, valueContactDetail=None, valueContactPoint=None, valueContributor=None, valueCount=None, valueDataRequirement=None, valueDate=None, valueDateTime=None, valueDecimal=None, valueDistance=None, valueDosage=None, valueDuration=None, valueExpression=None, valueHumanName=None, valueId=None, valueIdentifier=None, valueInstant=None, valueInteger=None, valueMarkdown=None, valueMeta=None, valueMoney=None, valueOid=None, valueParameterDefinition=None, valuePeriod=None, valuePositiveInt=None, valueQuantity=None, valueRange=None, valueRatio=None, valueReference=None, valueRelatedArtifact=None, valueSampledData=None, valueSignature=None, valueString=None, valueTime=None, valueTiming=None, valueTriggerDefinition=None, valueUnsignedInt=None, valueUri=None, valueUrl=None, valueUsageContext=None, valueUuid=None)]
Coverage ['http://hl7.org/fhir/us/core/StructureDefinition/us-core-coverage|9.0.0-ballot']
'http://hl7.org/fhir/us/core/StructureDefinition/us-core-coverage|9.0.0-ballot'
0 resource_type='FHIRPrimitiveExtension' fhir_comments=None id=None extension=[Extension(resource_type='Extension', fhir_comments=None, extension=None, id=None, url='http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation', valueAddress=None, valueAge=None, valueAnnotation=None, valueAttachment=None, valueBase64Binary=None, valueBoolean=None, valueCanonical=None, valueCode='SHALL', valueCodeableConcept=None, valueCoding=None, valueContactDetail=None, valueContactPoint=None, valueContributor=None, valueCount=None, valueDataRequirement=None, valueDate=None, valueDateTime=None, valueDecimal=None, valueDistance=None, valueDosage=None, valueDuration=None, valueExpression=None, valueHumanName=None, valueId=None, valueIdentifier=None, valueInstant=None, valueInteger=None, valueMarkdown=None, valueMeta=None, valueMoney=None, valueOid=None, valueParameterDefinition=None, valuePeriod=None, valuePositiveInt=None, valueQuantity=None, valueRange=None, valueRatio=None, valueReference=None, valueRelatedArtifact=None, valueSampledData=None, valueSignature=None, valueString=None, valueTime=None, valueTiming=None, valueTriggerDefinition=None, valueUnsignedInt=None, valueUri=None, valueUrl=None, valueUsageContext=None, valueUuid=None)]
Device ['http://hl7.org/fhir/us/core/StructureDefinition/us-core-device|9.0.0-ballot']
'http://hl7.org/fhir/us/core/StructureDefinition/us-core-device|9.0.0-ballot'
0 resource_type='FHIRPrimitiveExtension' fhir_comments=None id=None extension=[Extension(resource_type='Extension', fhir_comments=None, extension=None, id=None, url='http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation', valueAddress=None, valueAge=None, valueAnnotation=None, valueAttachment=None, valueBase64Binary=None, valueBoolean=None, valueCanonical=None, valueCode='SHALL', valueCodeableConcept=None, valueCoding=None, valueContactDetail=None, valueContactPoint=None, valueContributor=None, valueCount=None, valueDataRequirement=None, valueDate=None, valueDateTime=None, valueDecimal=None, valueDistance=None, valueDosage=None, valueDuration=None, valueExpression=None, valueHumanName=None, valueId=None, valueIdentifier=None, valueInstant=None, valueInteger=None, valueMarkdown=None, valueMeta=None, valueMoney=None, valueOid=None, valueParameterDefinition=None, valuePeriod=None, valuePositiveInt=None, valueQuantity=None, valueRange=None, valueRatio=None, valueReference=None, valueRelatedArtifact=None, valueSampledData=None, valueSignature=None, valueString=None, valueTime=None, valueTiming=None, valueTriggerDefinition=None, valueUnsignedInt=None, valueUri=None, valueUrl=None, valueUsageContext=None, valueUuid=None)]
DiagnosticReport ['http://hl7.org/fhir/us/core/StructureDefinition/us-core-diagnosticreport-note|9.0.0-ballot', 'http://hl7.org/fhir/us/core/StructureDefinition/us-core-diagnosticreport-lab|9.0.0-ballot']
'http://hl7.org/fhir/us/core/StructureDefinition/us-core-diagnosticreport-note|9.0.0-ballot'
0 resource_type='FHIRPrimitiveExtension' fhir_comments=None id=None extension=[Extension(resource_type='Extension', fhir_comments=None, extension=None, id=None, url='http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation', valueAddress=None, valueAge=None, valueAnnotation=None, valueAttachment=None, valueBase64Binary=None, valueBoolean=None, valueCanonical=None, valueCode='SHALL', valueCodeableConcept=None, valueCoding=None, valueContactDetail=None, valueContactPoint=None, valueContributor=None, valueCount=None, valueDataRequirement=None, valueDate=None, valueDateTime=None, valueDecimal=None, valueDistance=None, valueDosage=None, valueDuration=None, valueExpression=None, valueHumanName=None, valueId=None, valueIdentifier=None, valueInstant=None, valueInteger=None, valueMarkdown=None, valueMeta=None, valueMoney=None, valueOid=None, valueParameterDefinition=None, valuePeriod=None, valuePositiveInt=None, valueQuantity=None, valueRange=None, valueRatio=None, valueReference=None, valueRelatedArtifact=None, valueSampledData=None, valueSignature=None, valueString=None, valueTime=None, valueTiming=None, valueTriggerDefinition=None, valueUnsignedInt=None, valueUri=None, valueUrl=None, valueUsageContext=None, valueUuid=None)]
'http://hl7.org/fhir/us/core/StructureDefinition/us-core-diagnosticreport-lab|9.0.0-ballot'
1 resource_type='FHIRPrimitiveExtension' fhir_comments=None id=None extension=[Extension(resource_type='Extension', fhir_comments=None, extension=None, id=None, url='http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation', valueAddress=None, valueAge=None, valueAnnotation=None, valueAttachment=None, valueBase64Binary=None, valueBoolean=None, valueCanonical=None, valueCode='SHALL', valueCodeableConcept=None, valueCoding=None, valueContactDetail=None, valueContactPoint=None, valueContributor=None, valueCount=None, valueDataRequirement=None, valueDate=None, valueDateTime=None, valueDecimal=None, valueDistance=None, valueDosage=None, valueDuration=None, valueExpression=None, valueHumanName=None, valueId=None, valueIdentifier=None, valueInstant=None, valueInteger=None, valueMarkdown=None, valueMeta=None, valueMoney=None, valueOid=None, valueParameterDefinition=None, valuePeriod=None, valuePositiveInt=None, valueQuantity=None, valueRange=None, valueRatio=None, valueReference=None, valueRelatedArtifact=None, valueSampledData=None, valueSignature=None, valueString=None, valueTime=None, valueTiming=None, valueTriggerDefinition=None, valueUnsignedInt=None, valueUri=None, valueUrl=None, valueUsageContext=None, valueUuid=None)]
DocumentReference ['http://hl7.org/fhir/us/core/StructureDefinition/us-core-documentreference|9.0.0-ballot', 'http://hl7.org/fhir/us/core/StructureDefinition/us-core-adi-documentreference|9.0.0-ballot']
'http://hl7.org/fhir/us/core/StructureDefinition/us-core-documentreference|9.0.0-ballot'
0 resource_type='FHIRPrimitiveExtension' fhir_comments=None id=None extension=[Extension(resource_type='Extension', fhir_comments=None, extension=None, id=None, url='http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation', valueAddress=None, valueAge=None, valueAnnotation=None, valueAttachment=None, valueBase64Binary=None, valueBoolean=None, valueCanonical=None, valueCode='SHALL', valueCodeableConcept=None, valueCoding=None, valueContactDetail=None, valueContactPoint=None, valueContributor=None, valueCount=None, valueDataRequirement=None, valueDate=None, valueDateTime=None, valueDecimal=None, valueDistance=None, valueDosage=None, valueDuration=None, valueExpression=None, valueHumanName=None, valueId=None, valueIdentifier=None, valueInstant=None, valueInteger=None, valueMarkdown=None, valueMeta=None, valueMoney=None, valueOid=None, valueParameterDefinition=None, valuePeriod=None, valuePositiveInt=None, valueQuantity=None, valueRange=None, valueRatio=None, valueReference=None, valueRelatedArtifact=None, valueSampledData=None, valueSignature=None, valueString=None, valueTime=None, valueTiming=None, valueTriggerDefinition=None, valueUnsignedInt=None, valueUri=None, valueUrl=None, valueUsageContext=None, valueUuid=None)]
'http://hl7.org/fhir/us/core/StructureDefinition/us-core-adi-documentreference|9.0.0-ballot'
1 resource_type='FHIRPrimitiveExtension' fhir_comments=None id=None extension=[Extension(resource_type='Extension', fhir_comments=None, extension=None, id=None, url='http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation', valueAddress=None, valueAge=None, valueAnnotation=None, valueAttachment=None, valueBase64Binary=None, valueBoolean=None, valueCanonical=None, valueCode='SHALL', valueCodeableConcept=None, valueCoding=None, valueContactDetail=None, valueContactPoint=None, valueContributor=None, valueCount=None, valueDataRequirement=None, valueDate=None, valueDateTime=None, valueDecimal=None, valueDistance=None, valueDosage=None, valueDuration=None, valueExpression=None, valueHumanName=None, valueId=None, valueIdentifier=None, valueInstant=None, valueInteger=None, valueMarkdown=None, valueMeta=None, valueMoney=None, valueOid=None, valueParameterDefinition=None, valuePeriod=None, valuePositiveInt=None, valueQuantity=None, valueRange=None, valueRatio=None, valueReference=None, valueRelatedArtifact=None, valueSampledData=None, valueSignature=None, valueString=None, valueTime=None, valueTiming=None, valueTriggerDefinition=None, valueUnsignedInt=None, valueUri=None, valueUrl=None, valueUsageContext=None, valueUuid=None)]
---- no addin extensions found-----
Encounter ['http://hl7.org/fhir/us/core/StructureDefinition/us-core-encounter|9.0.0-ballot']
'http://hl7.org/fhir/us/core/StructureDefinition/us-core-encounter|9.0.0-ballot'
0 resource_type='FHIRPrimitiveExtension' fhir_comments=None id=None extension=[Extension(resource_type='Extension', fhir_comments=None, extension=None, id=None, url='http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation', valueAddress=None, valueAge=None, valueAnnotation=None, valueAttachment=None, valueBase64Binary=None, valueBoolean=None, valueCanonical=None, valueCode='SHALL', valueCodeableConcept=None, valueCoding=None, valueContactDetail=None, valueContactPoint=None, valueContributor=None, valueCount=None, valueDataRequirement=None, valueDate=None, valueDateTime=None, valueDecimal=None, valueDistance=None, valueDosage=None, valueDuration=None, valueExpression=None, valueHumanName=None, valueId=None, valueIdentifier=None, valueInstant=None, valueInteger=None, valueMarkdown=None, valueMeta=None, valueMoney=None, valueOid=None, valueParameterDefinition=None, valuePeriod=None, valuePositiveInt=None, valueQuantity=None, valueRange=None, valueRatio=None, valueReference=None, valueRelatedArtifact=None, valueSampledData=None, valueSignature=None, valueString=None, valueTime=None, valueTiming=None, valueTriggerDefinition=None, valueUnsignedInt=None, valueUri=None, valueUrl=None, valueUsageContext=None, valueUuid=None)]
Endpoint []
No Profiles for " Endpoint"
FamilyMemberHistory ['http://hl7.org/fhir/us/core/StructureDefinition/us-core-familymemberhistory|9.0.0-ballot']
'http://hl7.org/fhir/us/core/StructureDefinition/us-core-familymemberhistory|9.0.0-ballot'
0 resource_type='FHIRPrimitiveExtension' fhir_comments=None id=None extension=[Extension(resource_type='Extension', fhir_comments=None, extension=None, id=None, url='http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation', valueAddress=None, valueAge=None, valueAnnotation=None, valueAttachment=None, valueBase64Binary=None, valueBoolean=None, valueCanonical=None, valueCode='SHALL', valueCodeableConcept=None, valueCoding=None, valueContactDetail=None, valueContactPoint=None, valueContributor=None, valueCount=None, valueDataRequirement=None, valueDate=None, valueDateTime=None, valueDecimal=None, valueDistance=None, valueDosage=None, valueDuration=None, valueExpression=None, valueHumanName=None, valueId=None, valueIdentifier=None, valueInstant=None, valueInteger=None, valueMarkdown=None, valueMeta=None, valueMoney=None, valueOid=None, valueParameterDefinition=None, valuePeriod=None, valuePositiveInt=None, valueQuantity=None, valueRange=None, valueRatio=None, valueReference=None, valueRelatedArtifact=None, valueSampledData=None, valueSignature=None, valueString=None, valueTime=None, valueTiming=None, valueTriggerDefinition=None, valueUnsignedInt=None, valueUri=None, valueUrl=None, valueUsageContext=None, valueUuid=None)]
Goal ['http://hl7.org/fhir/us/core/StructureDefinition/us-core-goal|9.0.0-ballot']
'http://hl7.org/fhir/us/core/StructureDefinition/us-core-goal|9.0.0-ballot'

In [83]:
 #validate and write to file
if validate_me:
    print('...validating')
    r = validate(cs)
    display(HTML(f'<h1>Validation output</h1><h3>Status Code = {r.status_code}</h3> {r.json()["text"]["div"]}'))

### Create Narrative

- Using Jinja2 Template create xhtml for narrative

In [84]:
if(add_narrative):
    #### First: Get spec_internal from package.tgz a json file which includes canonical to local relative page links
    #### Note for this to work you have to have a working build that already contains all the needed artifacts.
    import tarfile
    package_path = Path.cwd() / 'tarfiles'/'package.tgz'  #get_si(path)
    print(package_path)
    def get_si(package_path):
        with tarfile.open(package_path, mode='r') as tf:
            # pprint(tf.getnames())
            f = tf.extractfile('package/other/spec.internals')
            r = f.read()
            return (loads(r))


    def get_si3(path):
        tf = get(path)
        if tf.status_code == 200:
            # print(f'get tarfile from {ig_package_tar_path}')
            return tf

    # "e.g. https://build.fhir.org/ig/HL7/davinci-deqm/package.tgz"
    try:
        # print(f'get tarfile from {ig_package_tar_path}')
        tf= get_si3(ig_package_tar_path) # get from remote server

    except:
        print("run build in auto-builder first and check remote package file")
        # print(f"use local package file from build file  = {ig_source_path.replace('/input/', '/output/')}package.tgz")
        # package_path = f"{ig_source_path.replace('/input/', '/output/')}package.tgz"

    else:
        print(f'get tarfile from {ig_package_tar_path}')
        package_path.write_bytes(tf.content)    #save in temp file

    si = get_si(package_path) #unpack from file

    path_map = si['paths']
    # print(f'path_map = {dumps(path_map, indent=2)}')



    #### Then Use Jinja2 template to create narrative

    in_path = ''
    in_file = 'R4capabilitystatement-server.j2'
    print(cs.date)
    # if add_ms_references_summary: # get Must Support references from ms_references module if available to create summary table of required references
    #     import ms_references
    #     ms_references_summary = ms_references.get_references_summary()
    # else:
    #     print('No ms_references module found')
    #     ms_references_summary = None

    def markdown(text, *args, **kwargs):
        return commonmark(text, *args, **kwargs)

    env = Environment(
        loader=FileSystemLoader(searchpath = in_path),
        autoescape=select_autoescape(['html','xml','xhtml','j2','md'],),
        trim_blocks = True,
        lstrip_blocks = True,
        )

    env.filters['markdown'] = markdown

    # env.filters['markdown'] = lambda text: markdown.markdown(text, extensions=['extra'])

    template = env.get_template(in_file)

    sp_map = {sp.code:sp.type for sp in df_sp.itertuples(index=True)}
    pname_map = {p.Profile:p.Name for p in df_profiles.itertuples(index=True)}
    # print(f'pname_map = {pname_map}')


    purl_map = {p.Profile:p.url if p.url not in none_list else p.Profile for p in df_profiles.itertuples(index=True)}

    igname_map = {ig.canonical:ig.name for ig in df_igs.itertuples(index=True)}
    igurl_map = {ig.canonical:ig.url if ig.url not in none_list else ig.canonical for ig in df_igs.itertuples(index=True)}
    csname_map = {cs.canonical:cs.name for cs in df_capstatements.itertuples(index=True)}
    csurl_map = {cs.canonical:cs.url if cs.url not in none_list else cs.canonical for cs in df_capstatements.itertuples(index=True)}
    # print(csurl_map)
    # print([i for i in df_capstatements.itertuples(index=True)])
    rendered = template.render(cs=cs, path_map=path_map, pname_map=pname_map, purl_map=purl_map, sp_map=sp_map,
                            csname_map=csname_map, csurl_map=csurl_map, igname_map=igname_map, igurl_map=igurl_map,) # ms_references_summary = ms_references_summary,)
    # print(rendered)



    ### Minify the xhtml

    def x_minify(xhtml):
        h_min=minify(xhtml, remove_optional_attribute_quotes=False, remove_comments=True)
        x_min = h_min.replace('<br>','<br />')
        x_min = x_min.replace('<hr>','<hr />')
        return x_min

    mini = x_minify(rendered)
    #print(type(mini))
    #display(HTML(rendered))
    display(HTML(mini))

    '''
    #======== write to temp file to debug =======
    path = Path.cwd() / 'debug' / 'narrative_pre.xhtml'
    path.write_text(rendered, encoding="utf-8")
    path = Path.cwd() / 'debug' / 'narrative_mini_pre.xhtml'
    path.write_text(mini, encoding="utf-8")
    #===================================================
    '''
    narr = construct_fhir_element('Narrative', dict(
            status = 'additional', #'generated'
            div = mini,
            ))
    cs.text = narr
    #print(cs.json(indent=2))
else:
    print('=====================')
    print('NO NARRATIVE ADDED')
    print('=====================')

/Users/ehaas/Documents/Python/Jupyter/MyNotebooks/CapStatement/tarfiles/package.tgz
get tarfile from http://build.fhir.org/ig/HL7/US-Core/package.tgz
2025-12-19 19:16:08.871976-08:00

### validate again

In [ ]:
if validate_me:
    print('...validating')
    r = validate(cs)
    d = display(HTML(f'<h1>Validation output</h1><h3>Status Code = {r.status_code}</h3> {r.json()["text"]["div"]}'))

    #======== write to temp file to debug =======
    from html.parser import HTMLParser

    class HTMLFilter(HTMLParser):
        text = ""
        def handle_data(self, data):
            self.text += data

    f = HTMLFilter()
    f.feed(f'<h1>Validation output</h1><h3>Status Code = {r.status_code}</h3> {r.json()["text"]["div"]}')
    path = Path.cwd() / 'debug' / 'validation.txt'
    path.write_text(f.text, encoding="utf-8")
    #===================================================

In [86]:
# save to file
#save in ig_source folder
#ig_source_path = ''

path = Path.cwd()/ my_base / ig_source_path / 'resources' / f'capabilitystatement-{cs.id.lower()}.json'

# path = Path.cwd() /  'resources' / f'capabilitystatement-{cs.id.lower()}.json' # write locally


print(f'...........saving to file {path}............')
path.write_text(cs.json(indent=2))

...........saving to file /Users/ehaas/Documents/FHIR/US-Core/input/resources/capabilitystatement-us-core-client.json............

421167